config

diff --git a/.github/workflows/render-cv.yml b/.github/workflows/render-cv.yml
--- a/.github/workflows/render-cv.yml
+++ b/.github/workflows/render-cv.yml
@@ -42,7 +42,13 @@ jobs:
             echo "Missing RenderCV config file!"
             exit 1
           fi
-          rendercv render $cv_file --settings $settings
+          design=$(find $rendercv_dir -maxdepth 1 -type f \( -name "design.yaml" -o -name "design.yml" \))
+          locale=$(find $rendercv_dir -maxdepth 1 -type f \( -name "locale.yaml" -o -name "locale.yml" \))
+          if [ -z "$design" ] || [ -z "$locale" ]; then
+            echo "Missing RenderCV design or locale file!"
+            exit 1
+          fi
+          rendercv render $cv_file --settings $settings --design $design --locale-catalog $locale
           rm assets/rendercv/rendercv_output/*.typ
       - name: Upload rendercv_output as an artifact
         uses: actions/upload-artifact@v4
